package form.adminView;

import dao.ConnectionProvider;
import java.awt.Color;
import java.util.LinkedList;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import utility.UIUtils;

/**
 *
 * @author Sohaib Hasan
 */
public class payementRecords extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(payementRecords.class.getName());
    
    class payementNode{
        int House_no;
        String ownerName;
        String month;
        int year;
        boolean Payementstatus;
        String lastPaid;
        int amountDue;
        int amountPaid;
        payementNode next;
        
        public payementNode(int House_no, String ownerName, String month, int year,
                            boolean Payementstatus, String lastPaid, int amountDue, int amountPaid){
            
            this.House_no=House_no;
            this.Payementstatus=Payementstatus;
            this.amountDue=amountDue;
            this.amountPaid=amountPaid;
            this.lastPaid=lastPaid;
            this.month=month;
            this.year=year;
            this.ownerName=ownerName;
            this.next=null;
        }
    }//END OF NODE CLASS
    
    LinkedList<payementNode>[] houses = new LinkedList[135];
    
    
    public payementRecords() {   
        initComponents();
        this.getRootPane().setBorder(BorderFactory.createMatteBorder(3,3,3,3,Color.BLACK));        
        for (int i = 0; i < 135; i++) {
            houses[i] = new LinkedList<>();
        }

        if (jComboBox1.getItemCount() > 0) {
            this.month = (String) jComboBox1.getSelectedItem();
        }
        if (jComboBox2.getItemCount() > 0) {
            this.year = (String) jComboBox2.getSelectedItem();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new utility.RoundedPanel(20);
        jLabel2 = new javax.swing.JLabel();
        backbtn = new javax.swing.JButton();
        jPanel2 = new utility.RoundedPanel(20);
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        savebtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(2, 100, 182));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PAYEMENT RECORDS");

        backbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        backbtn.setText("BACK");
        backbtn.addActionListener(this::backbtnActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 300, Short.MAX_VALUE)
                .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "House no.", "Owner", "Month", "Year", "Payement Status", "Last Paid", "Amount Due"
            }
        ));
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getColumnModel().getColumn(6).setResizable(false);
        }

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "Feburary", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        jComboBox1.addActionListener(this::jComboBox1ActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Select a month:");

        savebtn.setBackground(new java.awt.Color(2, 100, 182));
        savebtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        savebtn.setForeground(new java.awt.Color(255, 255, 255));
        savebtn.setText("SAVE TO DATABASE");
        savebtn.addActionListener(this::savebtnActionPerformed);

        jButton1.setBackground(new java.awt.Color(2, 100, 182));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Load Data");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2025", "2026", "2027", "2028", "2029", "2030", " " }));
        jComboBox2.addActionListener(this::jComboBox2ActionPerformed);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Select an year:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 718, Short.MAX_VALUE)
                .addGap(24, 24, 24))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(146, 146, 146)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(savebtn)
                        .addGap(142, 142, 142)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(savebtn)
                    .addComponent(jButton1))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {
        dispose();
    }
    
    String month = null;
    String getMonth(){return month;}
    
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
       this.month = (String) jComboBox1.getSelectedItem();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
        saveDataToDatabase();
    }//GEN-LAST:event_savebtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         loadDataFromDatabase();
    }//GEN-LAST:event_jButton1ActionPerformed
    String year = null;
    String getYear(){return year;}
    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        this.year = (String) jComboBox2.getSelectedItem();
    }//GEN-LAST:event_jComboBox2ActionPerformed

    //helper function
    private void loadDataFromDatabase() {
       
        for (int i = 0; i < 135; i++) {
            houses[i].clear();
        }
        
         String query = """
             SELECT h.house_no, h.owner_name,
                 p.payment_status, p.last_paid, p.amount_due, p.amount_paid
            FROM houses h
            LEFT JOIN payments p
            ON h.house_no = p.house_no
            AND p.month = ?
            AND p.year = ?
            ORDER BY h.house_no
            """;
        
        Connection con = null;
        PreparedStatement ps = null;
        ResultSet rs = null;
        
        try {
            con = ConnectionProvider.getcon();
            ps = con.prepareStatement(query);
            ps.setString(1, this.month);
            ps.setInt(2, Integer.parseInt(this.year.trim()));
            
            rs = ps.executeQuery();
            
            while (rs.next()) {
                int houseNo = rs.getInt("house_no");
                String ownerName = rs.getString("owner_name");
                int paymentStatusInt = rs.getInt("payment_status");
                boolean paymentStatusWasNull = rs.wasNull();
                String lastPaid = rs.getString("last_paid");
                int amountDue = rs.getInt("amount_due");
                int amountPaid = rs.getInt("amount_paid");

                if (ownerName == null || ownerName.trim().isEmpty()) {
                    ownerName = "N/A";
                }
                
                if (lastPaid == null) {
                    lastPaid = "N/A";
                }

                boolean isPaid = !paymentStatusWasNull && paymentStatusInt == 1;
                int yearInt = Integer.parseInt(this.year.trim());
                
                payementNode newNode = new payementNode(
                    houseNo, ownerName, this.month, yearInt, isPaid, lastPaid, amountDue, amountPaid
                );
                
                int index = houseNo - 1;
                if (index >= 0 && index < 135) {
                    houses[index].add(newNode);
                }
            }
            refreshTableFromLinkedList();
            
            JOptionPane.showMessageDialog(this, "Data loaded successfully for " + month + " " + year);
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error loading data: " + ex.getMessage());
        } finally {
            try {
                if (rs != null) rs.close();
                if (ps != null) ps.close();
                if (con != null) con.close();
            } catch (SQLException ex) {
            }
        }
    }
    
    
    private void refreshTableFromLinkedList() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
       
        for (int i = 0; i < 135; i++) {
            int houseNo = i + 1;  
            
            if (houses[i] != null && !houses[i].isEmpty()) {
                payementNode node = houses[i].getFirst();
                String statusText = node.Payementstatus ? "Paid" : "Unpaid";

                String ownerText = (node.ownerName == null || node.ownerName.trim().isEmpty())
                    ? "N/A"
                    : node.ownerName;
                
                model.addRow(new Object[]{
                    node.House_no,
                    ownerText,
                    node.month,
                    node.year,
                    statusText,
                    node.lastPaid,
                    node.amountDue,
                    node.amountPaid
                });
            } else {
                int yearInt = 2025; // default
                try {
                    yearInt = Integer.parseInt(this.year.trim());
                } catch (NumberFormatException e) {
                 
                }
                model.addRow(new Object[]{
                    houseNo,
                    "N/A",
                    this.month,
                    yearInt,
                    "Unpaid",
                    "N/A",
                    0,
                    0
                });
            }
        }
    }
    
    
    private void saveDataToDatabase() {
        if (jTable1.isEditing() && jTable1.getCellEditor() != null) {
            jTable1.getCellEditor().stopCellEditing();
        }
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int rowCount = model.getRowCount();
        
        Connection con = null;
        PreparedStatement psCheck = null;
        PreparedStatement psInsert = null;
        PreparedStatement psUpdate = null;
        
        try {
            con = ConnectionProvider.getcon();
            con.setAutoCommit(false); 
            
            String checkQuery = "SELECT * FROM payments WHERE house_no = ? AND month = ? AND year = ?";
            String insertQuery = "INSERT INTO payments (house_no, month, year, payment_status, last_paid, amount_due, amount_paid) VALUES (?, ?, ?, ?, ?, ?, ?)";
            String updateQuery = "UPDATE payments SET payment_status = ?, last_paid = ?, amount_due = ?, amount_paid = ? WHERE house_no = ? AND month = ? AND year = ?";
            
            psCheck = con.prepareStatement(checkQuery);
            psInsert = con.prepareStatement(insertQuery);
            psUpdate = con.prepareStatement(updateQuery);
            
            int savedCount = 0;

            for (int row = 0; row < rowCount; row++) {
                int houseNo = getIntFromTable(model, row, 0);
                String ownerName = getStringFromTable(model, row, 1);
                String monthVal = getStringFromTable(model, row, 2);
                int yearInt = getIntFromTable(model, row, 3);
                String paymentStatus = getStringFromTable(model, row, 4);
                String lastPaid = getStringFromTable(model, row, 5);
                int amountDue = getIntFromTable(model, row, 6);
                int amountPaid = getIntFromTable(model, row, 7);

                if (houseNo <= 0) {
                    continue;
                }
    
                boolean isPaid = "Paid".equalsIgnoreCase(paymentStatus);
                boolean hasLastPaidDate = lastPaid != null && !lastPaid.isEmpty() && !"N/A".equalsIgnoreCase(lastPaid);
                boolean hasAmountDue = amountDue > 0;
                boolean hasAmountPaid = amountPaid > 0;
                
                if (!isPaid && !hasLastPaidDate && !hasAmountDue && !hasAmountPaid) {
                    continue;
                }

                int index = houseNo - 1;
                if (index >= 0 && index < 135) {
                    houses[index].clear();
                    payementNode newNode = new payementNode(
                        houseNo, ownerName, monthVal, yearInt, isPaid, lastPaid, amountDue, amountPaid
                    );
                    houses[index].add(newNode);
                }
                
                psCheck.setInt(1, houseNo);
                psCheck.setString(2, monthVal);
                psCheck.setInt(3, yearInt);
                ResultSet rs = psCheck.executeQuery();
                
                if (rs.next()) {
                    psUpdate.setInt(1, isPaid ? 1 : 0);
                    if (!hasLastPaidDate) {
                        psUpdate.setNull(2, java.sql.Types.DATE);
                    } else {
                        psUpdate.setString(2, lastPaid);
                    }
                    psUpdate.setInt(3, amountDue);
                    psUpdate.setInt(4, amountPaid);
                    psUpdate.setInt(5, houseNo);
                    psUpdate.setString(6, monthVal);
                    psUpdate.setInt(7, yearInt);
                    psUpdate.executeUpdate();
                } else {
                    psInsert.setInt(1, houseNo);
                    psInsert.setString(2, monthVal);
                    psInsert.setInt(3, yearInt);
                    psInsert.setInt(4, isPaid ? 1 : 0);
                    if (!hasLastPaidDate) {
                        psInsert.setNull(5, java.sql.Types.DATE);
                    } else {
                        psInsert.setString(5, lastPaid);
                    }
                    psInsert.setInt(6, amountDue);
                    psInsert.setInt(7, amountPaid);
                    psInsert.executeUpdate();
                }
                rs.close();
                savedCount++;
            }
            
            con.commit();  
            JOptionPane.showMessageDialog(this, savedCount + " records saved successfully!");
            
        } catch (SQLException ex) {
          
            try {
                if (con != null) con.rollback();
            } catch (SQLException rollbackEx) {
               
            }
            JOptionPane.showMessageDialog(this, "Error saving data: " + ex.getMessage());
        } finally {
            try {
                if (psCheck != null) psCheck.close();
                if (psInsert != null) psInsert.close();
                if (psUpdate != null) psUpdate.close();
                if (con != null) {
                    con.setAutoCommit(true); 
                    con.close();
                }
            } catch (SQLException ex) {
        
            }
        }
    }
    
    private int getIntFromTable(DefaultTableModel model, int row, int col) {
        Object value = model.getValueAt(row, col);
        if (value == null) return 0;
        if (value instanceof Integer) return (Integer) value;
        if (value instanceof Number) return ((Number) value).intValue();
        try {
            String text = value.toString().trim();
            if (text.isEmpty()) return 0;
            text = text.replace(",", "");
            text = text.replaceAll("[^0-9-]", "");
            if (text.isEmpty() || "-".equals(text)) return 0;
            return Integer.parseInt(text);
        } catch (NumberFormatException e) {
            return 0;
        }
    }
    
    private String getStringFromTable(DefaultTableModel model, int row, int col) {
        Object value = model.getValueAt(row, col);
        if (value == null) return "";
        return value.toString().trim();
    }
    
    private double getDoubleFromTable(DefaultTableModel model, int row, int col) {
        Object value = model.getValueAt(row, col);
        if (value == null) return 0.0;
        if (value instanceof Double) return (Double) value;
        if (value instanceof Integer) return ((Integer) value).doubleValue();
        try {
            return Double.parseDouble(value.toString().trim());
        } catch (NumberFormatException e) {
            return 0.0;
        }
    }
    
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        UIUtils.applyFlatLafAndRefresh();
        java.awt.EventQueue.invokeLater(() -> new payementRecords().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton savebtn;
    // End of variables declaration//GEN-END:variables
}
